[tools]
opentofu = "1.11.5"
terraform-docs = "latest"

# Internal
"go:github.com/project-init/devex/cmd/release" = "v0.7.0"

[env]
MISE_DISABLE_BACKENDS = "aqua,ubi"

[settings]
experimental = true

# Lint and Format

[tasks.format]
run = "tofu fmt -recursive"

# Documentation

[tasks.docs]
run = "terraform-docs ."
